//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTask3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

    public partial class Person
    {
        public Person()
        {
            this.Orders = new HashSet<Order>();
        }

        public int ID { get; set; }
        [Required]
        [StringLength(12, ErrorMessage = "The Max Character of Name is 12 characters")]
        [DisplayName("First Name")]
        public string First_Name { get; set; }
        [DisplayName("Last Name")]
        [Required]
        [StringLength(12, ErrorMessage = "The Max Character of Name is 12 characters")]

        public string Last_Name { get; set; }
        [Required]
        [EmailAddress]
        [DisplayName("E mail")]
        public string E_mail { get; set; }
        [Required]
        [RegularExpression(@"^(0)?(77|78|79)\d{7}$", ErrorMessage = "Number must be Jordanian")]
        public Nullable<int> Phone { get; set; }
        [Required]
        [Range(18, 50)]

        public Nullable<int> Age { get; set; }
        [Required]
        [MaxLength(10), MinLength(1)]
        [DisplayName("Job Title")]

        public string JobTitle { get; set; }

        public Nullable<bool> Gender { get; set; }
        public string image { get; set; }
        public string CV { get; set; }
        public string GenderDisplay
        {
            get
            {
                if (Gender == null)
                {
                    return "Not specified";
                }
                else
                {
                    return Gender == true ? "Male" : "Female";
                }
            }
        }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }





    }
}
